# Generated by Django 3.2.8 on 2023-01-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('type', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('years', models.CharField(max_length=50, null=True)),
                ('fuel', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
