# Generated by Django 3.2.8 on 2023-01-15 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='fuel',
        ),
    ]
