# Generated by Django 3.2.8 on 2023-01-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0002_remove_ship_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='País de Origen'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='description',
            field=models.TextField(null=True, verbose_name='Descripción de la Nave'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Imagen de la Nave'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Nave'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='type',
            field=models.CharField(max_length=100, null=True, verbose_name='Tipo de Nave'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='years',
            field=models.CharField(max_length=50, null=True, verbose_name='Años de Operación'),
        ),
    ]
